### ISSUE TITLE
Are there any movements?

### ISSUE THREAD

**Issue by Piterden** [komachi/freebogatov.org#23]
Hi, guys and ladies!

I wanted to know, had there any things happened till the last time?
When a court hearing is scheduled?

Thanx... )

**Comment by imShara** [comment]
Hi, arrest delayed to 31 january..

**Comment by Piterden** [comment]
Если это, просто, продлили срок содержания под стражей до 31 января, то это ничего не значит. Им ничто не мешает продлевать его снова и снова. И суд по определению меры пресечения - это просто формальность.

Если же на 31 января назначено слушание по его уголовному делу, то это уже "повижки".

Простите за русский, я не знаком со всеми этими терминами на английском языке.

**Comment by imShara** [comment]
https://rublacklist.net/33106/

«Суд постановил в отношении Богатова продлить меру пресечения в виде домашнего ареста на три месяца, то есть до 31 января 2018 года, с ограничением ранее наложенных запретов».

Что значит простите за русский? :) Просто отвечаем на том языке, на котором был задан вопрос.

**Comment by Piterden** [comment]
Пфух) Ну нормально! То, что в кавычках ^ называется "нагнали" и означает отпустили.

Ну поздравляю!!!

Спасибо, чет я совсем заработался... )
> Что значит простите за русский?

Как-то, принято тут по-английски, просто...
